
language: java

jdk: oraclejdk8

sudo: true

cache:
  directories:
    - ~/.m2/repository
 
before_install:
  - sudo apt-get update -q
  - sudo apt-get install haveged
  - sudo service haveged restart
  #- sudo apt-get install gnupg2
  - sudo apt-get install gnupg-agent

script: mvn --settings="settings.xml" clean verify
   
#after_success:
  # - build/before-deploy.sh
  # - build/deploy.sh

before_deploy:
  #- sudo killall -q ssh-agent gnupg-agent
  #- unset GPG_AGENT_INFO SSH_AGENT_PID SSH_AUTH_SOCK
  - eval $(gpg-agent --daemon --enable-ssh-support)

deploy:
  -
    provider: script
    script: build/deploy.sh
    skip_cleanup: true
    on:
      repo: spoofzu/DeepVioletTools
      tags: true
      jdk: oraclejdk8
  
# configure notifications (email, IRC, campfire etc)
# check results at https://webchat.freenode.net/
notifications:
  irc: "irc.freenode.org#deepviolettools"
  template:
      - '%{repository_slug}#%{build_number} (%{branch}) %{message} %{build_url}'
